services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:latest
    restart: unless-stopped
    networks:
      - gateway
      - miniflux_internal
    environment:
      DATABASE_URL: postgres://miniflux:${POSTGRES_PASSWORD}@db/miniflux?sslmode=disable
      RUN_MIGRATIONS: "1"
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: miniflux-postgres
    image: postgres:18
    restart: unless-stopped
    networks:
      - miniflux_internal
    environment:
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

volumes:
  miniflux-db:
    name: miniflux-postgres

networks:
  gateway:
    external: true
  miniflux_internal:
    external: true